# Pipeline CI pour l'application Django
name: Django CI

env:
  DOCKER_IMAGE: bvfode04/coaching-app  

# Déclenche le workflow sur push et pull request vers main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Linting (Flake8)
    runs-on: ubuntu-latest

    steps:
      # Récupère le code depuis le repo
    - name: Checkout du code
      uses: actions/checkout@v4

      # Configure Python 3.9
    - name: Configuration de Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
      # Installe Flake8 pour l'analyse de code
    - name: Installation de Flake8
      run: |
        python -m pip install --upgrade pip
        pip install flake8
      
      # Vérifie la qualité du code
    - name: Exécution de Flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  test:
    name: Tests Unitaires Django
    runs-on: ubuntu-latest
    needs: lint # Ce job attend que lint soit terminé

    steps:
      # Récupère le code du repository
    - name: Checkout du code
      uses: actions/checkout@v4

      # Configure Python
    - name: Configuration de Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

        # Installe les dépendances du projet
    - name: Installation des dépendances
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  

      # Lance les tests Django
    - name: Exécution des tests Django
      run: |
        python manage.py test

  build-and-push:
    name: Build et Push Docker Image
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Checkout du code
      uses: actions/checkout@v4
      # Configure Docker Buildx pour des builds optimisés
    - name: Configuration de Docker Buildx
      uses: docker/setup-buildx-action@v3
      # Se connecte à Docker Hub avec les secrets GitHub
    - name: Connexion à Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
      # Build l'image Docker et la push sur Docker Hub     
    - name: Build et Push de l'image Docker
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true  #Push l'image vers Docker Hub
        tags: |
          ${{ env.DOCKER_IMAGE }}:latest
          ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
        # Utilise le cache pour accélérer les builds
        cache-from: type=registry,ref=${{ env.DOCKER_IMAGE }}:buildcache
        cache-to: type=registry,ref=${{ env.DOCKER_IMAGE }}:buildcache,mode=max